# .github/workflows/update-feed.yml
name: Update product feed and sitemaps

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'products-template.xlsx'
      - 'generate_from_excel.py'
      - 'generate_feed.py'
      - 'generate_sitemap.py'
      - 'products/**'
      - 'templates/**'
      - 'requirements.txt'
      - 'index.html'
      - 'style.css'
      - 'robots.txt'
  schedule:
    - cron: '0 */12 * * *'   # run every 12 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-feed
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for accurate lastmod

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas openpyxl python-slugify beautifulsoup4 lxml requests feedgen
          fi

      - name: Generate product pages from Excel (optional)
        run: |
          if [ -f generate_from_excel.py ]; then
            python generate_from_excel.py
          else
            echo "generate_from_excel.py not found, skipping"
          fi

      - name: Generate product feed
        run: |
          if [ -f generate_feed.py ]; then
            python generate_feed.py
          else
            echo "generate_feed.py not found, skipping"
          fi

      - name: Generate sitemap(s)
        run: |
          if [ -f generate_sitemap.py ]; then
            python generate_sitemap.py
          else
            echo "generate_sitemap.py not found, skipping"
          fi

      - name: Optional: notify IndexNow
        if: ${{ env.INDEXNOW_KEY != '' }}
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
          HOST: sherow1982.github.io
          KEY_LOCATION: https://sherow1982.github.io/Kuwait-matjar/${{ secrets.INDEXNOW_KEY }}.txt
        run: |
          URLS="$(git diff --name-only HEAD~1..HEAD | grep -E '^products/.+\.html$' | sed -E 's#^products/#https://sherow1982.github.io/Kuwait-matjar/products/#')"
          if [ -n "$URLS" ]; then
            printf '{ "host":"%s","key":"%s","keyLocation":"%s","urlList":[%s] }\n' \
              "$HOST" "$INDEXNOW_KEY" "$KEY_LOCATION" "$(printf '"%s",' $URLS | sed 's/,$//')" \
              > indexnow.json
            curl -sS -X POST -H "Content-Type: application/json; charset=utf-8" \
              --data-binary @indexnow.json https://api.indexnow.org/indexnow || true
          else
            echo "No product URL changes to submit"
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add products/*.html products/products.json feed*.xml feed/**/*.xml sitemap-products*.xml sitemap-index.xml || true
          if git diff --staged --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "chore: update feed & sitemaps [skip ci]"
          git pull --rebase origin "$GITHUB_REF_NAME" || true
          git push
